name: cnb-ai-merge (reusable)

on:
  workflow_call:
    inputs:
      upstream_repo:        # 必填：上游仓 HTTPS
        required: true
        type: string
      cnb_repo_url:         # 必填：CNB 仓 HTTPS
        required: true
        type: string
      delete_ai_branch:     # 可选：成功后删除 GitHub 远端 ai/* 分支
        required: false
        type: boolean
        default: true
    secrets:
      CNB_GH_TOKEN:
        required: true

permissions:
  contents: write

jobs:
  merge-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Detect AI branch
        id: detect
        run: |
          # 触发 ref，例如 refs/heads/ai/2025-09-foo
          REF="${GITHUB_REF#refs/heads/}"
          echo "ai_branch=${REF}" >> "$GITHUB_OUTPUT"

      - name: Prepare remotes
        env:
          CNB_GH_TOKEN: ${{ secrets.CNB_GH_TOKEN }}
          CNB_REPO_URL: ${{ inputs.cnb_repo_url }}
        run: |
          set -e
          git remote add upstream "${{ inputs.upstream_repo }}" || true
          git fetch upstream --prune
          RAW="$CNB_REPO_URL"
          CNB_URL="${RAW/https:\/\//https:\/\/cnb:${CNB_GH_TOKEN}@}"
          git remote add cnb "$CNB_URL" || true
          git fetch cnb --prune

      - name: Start from CNB main or upstream main
        run: |
          set -e
          if git ls-remote --heads cnb main | grep -q main; then
            git checkout -b cnbr-main cnb/main
          else
            git checkout -b cnbr-main upstream/main
          fi

      - name: Merge CNB upstream then AI branch
        run: |
          set -e
          if git ls-remote --heads cnb upstream | grep -q upstream; then
            git pull --no-edit cnb upstream
          else
            git pull --no-edit upstream main
          fi
          # 合并触发时的 ai/* 本地分支
          git merge --no-ff --no-edit "${{ steps.detect.outputs.ai_branch }}"

      - name: Push to CNB main
        id: push_cnb
        env:
          CNB_GH_TOKEN: ${{ secrets.CNB_GH_TOKEN }}
          CNB_REPO_URL: ${{ inputs.cnb_repo_url }}
        run: |
          set -e
          NEW_HEAD="$(git rev-parse HEAD)"
          echo "new_head=${NEW_HEAD}" >> "$GITHUB_OUTPUT"
          RAW="$CNB_REPO_URL"
          CNB_URL="${RAW/https:\/\//https:\/\/cnb:${CNB_GH_TOKEN}@}"
          git push "$CNB_URL" HEAD:main

      - name: Verify CNB/main advanced
        id: verify
        env:
          CNB_GH_TOKEN: ${{ secrets.CNB_GH_TOKEN }}
          CNB_REPO_URL: ${{ inputs.cnb_repo_url }}
        run: |
          set -e
          RAW="$CNB_REPO_URL"
          CNB_URL="${RAW/https:\/\//https:\/\/cnb:${CNB_GH_TOKEN}@}"
          REMOTE_SHA="$(git ls-remote "$CNB_URL" refs/heads/main | awk '{print $1}')"
          echo "cnb_head=${REMOTE_SHA}" >> "$GITHUB_OUTPUT"
          test "$REMOTE_SHA" = "${{ steps.push_cnb.outputs.new_head }}"

      - name: Delete GitHub ai/* branch (remote)
        if: ${{ inputs.delete_ai_branch && startsWith(github.ref, 'refs/heads/ai/') && success() }}
        run: |
          git push origin :${{ steps.detect.outputs.ai_branch }}
