name: cnb-all (reusable)

on:
  workflow_call:
    inputs:
      upstream_repo:          # 必填：上游仓 HTTPS
        required: true
        type: string
      cnb_repo_url:           # 必填：CNB 仓 HTTPS
        required: true
        type: string
      fork_branch:            # 可选：fork 主分支名
        required: false
        type: string
        default: main
      push_fork_ff:           # 可选：是否快进 fork/main
        required: false
        type: boolean
        default: true
      open_pr_if_diverged:    # 可选：分叉时是否开 PR
        required: false
        type: boolean
        default: true
      delete_ai_branch:       # 可选：成功后删除 ai/* 远端分支
        required: false
        type: boolean
        default: true
    secrets:
      CNB_GH_TOKEN:
        required: true

jobs:
  # 只在 schedule / workflow_dispatch 时执行
  sync:
    if: github.event_name != 'push'
    uses: weu8/workflows/.github/workflows/cnb-sync.yml@main
    secrets: inherit
    with:
      upstream_repo:       ${{ inputs.upstream_repo }}
      cnb_repo_url:        ${{ inputs.cnb_repo_url }}
      fork_branch:         ${{ inputs.fork_branch }}
      push_fork_ff:        ${{ inputs.push_fork_ff }}
      open_pr_if_diverged: ${{ inputs.open_pr_if_diverged }}

  # 只在 ai/* push 时执行
  ai-merge:
    if: startsWith(github.ref, 'refs/heads/ai/')
    uses: weu8/workflows/.github/workflows/cnb-ai-merge.yml@main
    secrets: inherit
    with:
      upstream_repo:    ${{ inputs.upstream_repo }}
      cnb_repo_url:     ${{ inputs.cnb_repo_url }}
      delete_ai_branch: ${{ inputs.delete_ai_branch }}
